### ISSUE TITLE
training puffin on new CAGE tracks

### ISSUE THREAD

**Issue by gouthamatla** [jzhoulab/puffin#10]
Hi All, 

I have CAGE data from a tissue that is not represented in FANTOM or Encode. I would like to train puffin on that data. May I confirm I need to run https://github.com/jzhoulab/puffin_manuscript/blob/main/train/train_puffin_stage1.py script with appropriate bigwig files of fwd and rev CAGE signals  ? And providing correct tsses ? 

We also have different categories of CAGE peaks such as robust (strong) and permissive (weak) , tissue specific and ubiquitous promoters. Is there a way to train the model on different classes of promoters ?

**Comment by KseniiaDundyk** [comment]
Hi,
That’s right, if you want to identify the motifs you can train the first stage of the Puffin model using your bigwig data. If your data is human, you can still use the TSS list that was originally used to train Puffin. However, you might want to sort the list by TSS coverage in your data.  I assume, you probably have fewer samples than the original dataset, therefore Instead of using all 40K TSS, you may need to use only those TSS with good coverage. Additionally, you may need to adjust regularization parameters to account for the noisiness in your data.

Yes, you can train the model on different classes of promoters, you will need a different TSS list for each class.

Best,
Kseniia

**Comment by gouthamatla** [comment]
Fantastic. Thank you.
